/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'Food' : IDL.Null,
  'Tech' : IDL.Null,
  'Music' : IDL.Null,
});
export const Event = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : Category,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  'filterByCategory' : IDL.Func(
      [IDL.Vec(Category)],
      [IDL.Vec(Event)],
      ['query'],
    ),
  'listEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'Food' : IDL.Null,
    'Tech' : IDL.Null,
    'Music' : IDL.Null,
  });
  const Event = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : Category,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    'filterByCategory' : IDL.Func(
        [IDL.Vec(Category)],
        [IDL.Vec(Event)],
        ['query'],
      ),
    'listEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };